# Generated by Django 3.2.3 on 2021-05-21 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 20, 4, 49, 2, 739653, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
